
language: node_js
node_js:
  - "6"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  npm install -g codecov

script:
  - npm run test

afte_success:
  - npm run cover

cache:
  yarn: true