language: node_js

node_js:
  - "6"

env:
  - USERNAME=piyushvijay.1997@gmail.com
  - PASSWORD=random
  - JWT_SECRET=my-jwt-secret
  - SALT_ROUNDS=10
  - COOKIE_NAME=random-cookie
  - COOKIE_SECRET=random-secret
  - DB_HOST=localhost
  - DB_USER=travis
  - DB_PASSWORD=
  - DB_NAME=test

services:
  - mysql

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - mysql -e 'CREATE DATABASE IF NOT EXIST `test`;'

afte_success:
  - npm run cover

cache:
  yarn: true