language: node_js

node_js:
  - "6"

sudo: false

env:
  - PASSWORD=random JWT_SECRET=my-jwt-secret COOKIE_NAME=random-cookie COOKIE_SECRET=random-secret DB_HOST=localhost DB_USER=travis DB_PASSWORD= DB_NAME=test

services:
  - mysql

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - mysql -e 'CREATE DATABASE `test`;'

afte_success:
  - npm run cover

cache:
  yarn: true